services:
  n8n-editor:
    image: n8nio/n8n:latest
    container_name: n8n-editor-queue
    restart: unless-stopped
    ports:
      - 5678:5678
    networks:
      - n8n-queue
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  n8n-workers:
    image: n8nio/n8n:latest
    container_name: n8n-workers-queue
    restart: unless-stopped
    ports:
      - 5676:5678
    networks:
      - n8n-queue
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: worker

  n8n-webhooks:
    image: n8nio/n8n:latest
    container_name: n8n-webhooks-queue
    restart: unless-stopped
    ports:
      - 5677:5678
    networks:
      - n8n-queue
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: webhook

  postgres:
    image: ankane/pgvector
    container_name: postgres-n8n-queue
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - n8n-queue

  redis:
    image: redis:alpine
    container_name: redis-n8n-queue
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - n8n-queue

networks:
  n8n-queue:
    driver: bridge
